### ISSUE TITLE
No module named 'adafruit_drv2605'

### ISSUE THREAD

**Issue by iooi** [adafruit/Adafruit_CircuitPython_DRV2605#7] opened 2018-09-25 06:42 UTC
I installed `adafruit-circuitpython-drv2605` OK on Raspberry Pi 3, following the steps in https://learn.adafruit.com/adafruit-drv2605-haptic-controller-breakout/python-circuitpython. But when I ran,

pi@raspberrypi:~/lis $ python3 drv2605_simpletest.py
Traceback (most recent call last):
  File "drv2605_simpletest.py", line 9, in <module>
    import adafruit_drv2605
ImportError: No module named 'adafruit_drv2605'

**Comment by ladyada** [comment] 2018-09-25 16:27
you probably installed the library with pip not pip3? :)

**Comment by iooi** [comment] 2018-09-25 16:44
I do installed via `sudo pip3 install adafruit-circuitpython-drv2605`

```
pi@raspberrypi:~/lis $ sudo pip3 install adafruit-circuitpython-drv2605
Requirement already satisfied: adafruit-circuitpython-drv2605 in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied: Adafruit-Blinka in /usr/local/lib/python3.5/dist-packages (from adafruit-circuitpython-drv2605)
Requirement already satisfied: adafruit-circuitpython-busdevice in /usr/local/lib/python3.5/dist-packages (from adafruit-circuitpython-drv2605)
Requirement already satisfied: rpi-ws281x>=4.0.0; platform_machine == "armv7l" in /usr/local/lib/python3.5/dist-packages (from Adafruit-Blinka->adafruit-circuitpython-drv2605)
Requirement already satisfied: Adafruit-GPIO in /usr/local/lib/python3.5/dist-packages (from Adafruit-Blinka->adafruit-circuitpython-drv2605)
Requirement already satisfied: adafruit-pureio in /usr/local/lib/python3.5/dist-packages (from Adafruit-GPIO->Adafruit-Blinka->adafruit-circuitpython-drv2605)
Requirement already satisfied: spidev in /usr/lib/python3/dist-packages (from Adafruit-GPIO->Adafruit-Blinka->adafruit-circuitpython-drv2605)
pi@raspberrypi:~/lis $
pi@raspberrypi:~/lis $
pi@raspberrypi:~/lis $
pi@raspberrypi:~/lis $ sudo python3 drv2605_simpletest.py
Traceback (most recent call last):
  File "drv2605_simpletest.py", line 9, in <module>
    import adafruit_drv2605
ImportError: No module named 'adafruit_drv2605'

```

**Comment by ladyada** [comment] 2018-09-25 16:52
then run `sudo python` for your code?

**Comment by iooi** [comment] 2018-09-25 17:00
No, I used `python3` to run. Please see my console output in previous comment. Could you please help?

**Comment by iooi** [comment] 2018-09-25 17:08
More info,

```
pi@raspberrypi:~/lis $ ls /usr/local/lib/python3.5/dist-packages
adafruit_blinka                                   bitbangio.py       __pycache__
Adafruit_Blinka-0.2.7.dist-info                   board.py           rpi_ws281x
adafruit_bus_device                               busio.py           rpi_ws281x-4.0.0.dist-info
adafruit_circuitpython_busdevice-2.2.5.dist-info  digitalio.py       _rpi_ws281x.cpython-35m-arm-linux-gnueabihf.so
adafruit_circuitpython_drv2605-1.1.0.dist-info    easy_install.py    setuptools
Adafruit_GPIO                                     microcontroller    setuptools-40.4.3.dist-info
Adafruit_GPIO-1.0.3.dist-info                     micropython.py     tests
Adafruit_PureIO                                   neopixel_write.py
Adafruit_PureIO-0.2.3.dist-info                   pkg_resources
```

**Comment by ladyada** [comment] 2018-09-25 17:27
use sudo python3

**Comment by iooi** [comment] 2018-09-25 17:30
I used `sudo python3`. :(

```
pi@raspberrypi:~/lis $ sudo python3 drv2605_simpletest.py
Traceback (most recent call last):
  File "drv2605_simpletest.py", line 9, in <module>
    import adafruit_drv2605
ImportError: No module named 'adafruit_drv2605'
```

**Comment by ladyada** [comment] 2018-09-25 17:31
i dont know what's up - its definietely installed. we can check it out later

**Comment by iooi** [comment] 2018-09-25 17:32
yes please. It's a new Raspberry Pi 3 B+ model.

**Comment by iooi** [comment] 2018-09-25 17:34
Could you please keep it open?

**Comment by iooi** [comment] 2018-09-25 17:34
Thanks!

**Comment by brennen** [comment] 2018-09-25 17:43
Ok, I can reproduce this.  Digging into why.

**Comment by brennen** [comment] 2018-09-25 20:21
So it looks like we have the wrong module altogether released as version 1.1.0 of this on PyPI, which is what's causing the breakage you see.  This is _probably_ my fault, somehow or another, although I'm not quite sure what happened.

Will sort, but in the meanwhile, you can probably install by cloning this repository and running `setup.py` manually:

```sh
git clone https://github.com/adafruit/Adafruit_CircuitPython_DRV2605.git
cd Adafruit_CircuitPython_DRV2605
python3 setup.py install
```

...use `sudo python3 setup.py install` if you want a systemwide install; otherwise the library will be installed just for your user.

**Comment by iooi** [comment] 2018-09-25 20:23
Thanks much for quick action, @brennen !

**Comment by iooi** [comment] 2018-09-25 20:44
After installing new lib, I got the following,

```
pi@raspberrypi:~/lis $ sudo python3 drv2605_simpletest.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/adafruit_bus_device/i2c_device.py", line 64, in __init__
    i2c.writeto(device_address, b'')
  File "/usr/local/lib/python3.5/dist-packages/busio.py", line 63, in writeto
    return self._i2c.writeto(address, buffer, stop=stop)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/raspi_23/i2c.py", line 38, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_PureIO/smbus.py", line 244, in write_bytes
    self._device.write(buf)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "drv2605_simpletest.py", line 14, in <module>
    drv = adafruit_drv2605.DRV2605(i2c)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_circuitpython_drv2605-0.9.1.dev1+gcf5e680-py3.5.egg/adafruit_drv2605.py", line 101, in __init__
  File "/usr/local/lib/python3.5/dist-packages/adafruit_bus_device/i2c_device.py", line 66, in __init__
    raise ValueError("No I2C device at address: %x" % device_address)
ValueError: No I2C device at address: 5a
pi@raspberrypi:~/lis $ ls /dev/i2c*
/dev/i2c-1
```

is it sth related to the library or controller?

**Comment by brennen** [comment] 2018-09-26 20:40
I've deleted the bogus release from PyPI; things _should_ be good at this point for future users.

cc: @kattni so you're aware of this one.

**Closed as completed by brennen** 2018-09-26 20:40 UTC
Labels: bug

**Comment by oriolgalceran** [comment] 2018-12-09 16:21
Same thing is still happening. Just installed adafruit-drv2605 and module not found.

**Comment by masynthetic** [comment] 2019-06-23 00:32
I am currently having the same issue on a Rasperry Pi 3. Installed using pip3 and running with python3, tried sudo/not sudo to no avail. The circuitPython stuff seems to be installing and importing fine however when trying to install this module like:

`sudo pip3 install adafruit-circuitpython-drv2605`

and got this nasty error.
![image](https://user-images.githubusercontent.com/18704981/59970108-4cfbd300-9513-11e9-89dd-2bc84b199957.png)

I didn't change anything but just tried running again later and it seemingly installed fine, however it is still failing to import. Any ideas? Should I just use the workaround above to clone and run setup or should this be resolved?

**Comment by masynthetic** [comment] 2019-06-23 00:50
Workaround seems to pass :) but FYI this does still seem to be an issue!

**Comment by caternuson** [comment] 2019-06-23 16:58
Try again. It may have been some kind of intermittent network issue.

I can't recreate.
```console
pi@raspberrypi:~ $ sudo pip3 install adafruit-circuitpython-drv2605
Collecting adafruit-circuitpython-drv2605
  Downloading https://www.piwheels.org/simple/adafruit-circuitpython-drv2605/adafruit_circuitpython_drv2605-1.1.2-py3-none-any.whl
Requirement already satisfied: adafruit-circuitpython-busdevice in /usr/local/lib/python3.5/dist-packages (from adafruit-circuitpython-drv2605)
Requirement already satisfied: Adafruit-Blinka in /usr/local/lib/python3.5/dist-packages (from adafruit-circuitpython-drv2605)
Requirement already satisfied: rpi-ws281x>=4.0.0; platform_machine == "armv7l" or platform_machine == "armv6l" in /usr/local/lib/python3.5/dist-packages (from Adafruit-Blinka->adafruit-circuitpython-drv2605)
Requirement already satisfied: RPi.GPIO; platform_machine == "armv7l" or platform_machine == "armv6l" in /usr/local/lib/python3.5/dist-packages (from Adafruit-Blinka->adafruit-circuitpython-drv2605)
Requirement already satisfied: Adafruit-PlatformDetect in /usr/local/lib/python3.5/dist-packages (from Adafruit-Blinka->adafruit-circuitpython-drv2605)
Requirement already satisfied: Adafruit-PureIO in /usr/local/lib/python3.5/dist-packages (from Adafruit-Blinka->adafruit-circuitpython-drv2605)
Requirement already satisfied: sysv-ipc; platform_system != "Windows" in /usr/local/lib/python3.5/dist-packages (from Adafruit-Blinka->adafruit-circuitpython-drv2605)
Requirement already satisfied: spidev; sys_platform == "linux" in /usr/local/lib/python3.5/dist-packages (from Adafruit-Blinka->adafruit-circuitpython-drv2605)
Installing collected packages: adafruit-circuitpython-drv2605
Successfully installed adafruit-circuitpython-drv2605-1.1.2
pi@raspberrypi:~ $
```

**Comment by caternuson** [comment] 2019-06-23 17:05
Hmm. But then I can't import after the install. 
```console
pi@raspberrypi:~ $ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import adafruit_drv2605
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'adafruit_drv2605'
>>> exit()
pi@raspberrypi:~ $ sudo python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import adafruit_drv2605
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'adafruit_drv2605'
>>> exit()
pi@raspberrypi:~ $
```
